
 kind: "Deployment"
  apiVersion: "apps/v1"
  metadata:
    name: "front-deployment-1.0.77"
    labels:
      application: "xl-demo-uccm-app"
      component: "front"
    annotations:
      xldeploy.com/version: "1.0.77"
      xldeploy.com/environment: "xl-demo-staging"
  spec:
    replicas: 1
    strategy:
      type: "RollingUpdate"
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
    selector:
      matchLabels:
        application: "xl-demo-uccm-app"
        component: "front"
    template:
      metadata:
        name: "front-deployment-1.0.77"
        labels:
          application: "xl-demo-uccm-app"
          component: "front"
          version: "1.0.77"
      spec:
        volumes:
          - name: "front-config-d-89083250-f-3d7f4bbbc0-configmap-volume"
            configMap:
              name: "front-config-d-89083250-f-3d7f4bbbc0-configmap"
              defaultMode: 420
        imagePullSecrets: []
        containers:
          - name: "front"
            image: "localhost:5000/xl-demo-frontend:1.0.77"
            ports:
              - containerPort: 8000
                protocol: "TCP"
            env:
              - name: "BACKEND_ENDPOINT"
                value: "http://back-web-service"
              - name: "FEATURE"
                value: "UCCM <b>staging</b>-xl-demo-frontend:1.0.77"
            volumeMounts:
              - name: "front-config-d-89083250-f-3d7f4bbbc0-configmap-volume"
                readOnly: true
                mountPath: "/opt/config/data"
            terminationMessagePath: "/dev/termination-log"
            terminationMessagePolicy: "File"
            imagePullPolicy: "IfNotPresent"
        restartPolicy: "Always"
        terminationGracePeriodSeconds: 30

