apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Containers
  type: core.Directory
  children:
    - name: xl-demo-backend
      type: udm.Application
      children:
      - name: !value appversion
        type: udm.DeploymentPackage
        deployables:
        - name: backend.yaml
          type: k8s.ResourcesFile
          file: !file manifests/backend.yml
