apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: 'backend-primary'
  labels:
    stack: backend
    tier: '{{env}}'
spec:
  replicas: 1
  selector:
    matchLabels:
      stack: backend
      tier: '{{env}}'
  template:
    metadata:
      labels:
        stack: backend
        tier: '{{env}}'
    spec:
      containers:
      - name: primary
        image: xl-demo-backend:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: backend
spec:
  selector:
    stack: backend
    tier: '{{env}}'
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
