apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'backend-{{ canary_type }}'
  labels:
    stack: backend
    tier: '{{env}}'
    canary: '{{is_canary}}'
spec:
  replicas: '{{replicas}}'
  selector:
    matchLabels:
      stack: backend
      tier: '{{env}}'
      canary: '{{is_canary}}'
  template:
    metadata:
      labels:
        stack: backend
        tier: '{{env}}'
        canary: '{{is_canary}}'
    spec:
      containers:
      - name: primary
        image: localhost:5000/backend:6
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: backend
spec:
  selector:
    stack: backend
    tier: '{{env}}'
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
