apiVersion: xl-deploy/v1
kind: Applications
spec:
  - name: xl-demo-uccm-app
    type: udm.Application
    children:
    - name: !value appversion
      type: udm.DeploymentPackage
      orchestrator:
      - sequential-by-deployed
      deployables:
      - name: back
        type: uccm.ContainerSpec
        image: !format localhost:5000/xl-demo-backend:%appversion%
        replicas: "1"
        profile: default
        ports:
        - name: web
          type: uccm.ContainerPortSpec
          containerPort: "8000"
          exposeAsService: True
          servicePort: "80"
      - name: front
        type: uccm.ContainerSpec
        image: !format localhost:5000/xl-demo-frontend:%appversion%
        profile: production
        replicas: 3
        env:
          BACKEND_ENDPOINT: http://back-web-service
          FEATURE: !format UCCM <b>{{env}}</b>-xl-demo-frontend:%appversion%
        ports:
        - name: web
          type: uccm.ContainerPortSpec
          containerPort: "8000"
          exposeAsService: True
          servicePort: "80"
          exposeAsIngress: True
      - name: test application availability
        type: smoketest.HttpRequestTest
        url: http://xl-demo-{{env}}.xl-demo-uccm-app.xebialabs.demo/
        expectedResponseText: Hello, world!

