apiVersion: xl-deploy/v1
kind: Applications
spec:
  - name: xl-demo-uccm-app
    type: udm.Application
    children:
    - name: !value appversion
      type: udm.DeploymentPackage
      orchestrator:
      - sequential-by-deployed
      deployables:
      - name: back
        type: uccm.ContainerSpec
        image: !format localhost:5000/xl-demo-backend:%appversion%
        replicas: "1"
        profile: production
        ports:
        - name: web
          type: uccm.ContainerPortSpec
          containerPort: "8000"
          servicePort: "80"
      - name: front
        type: uccm.ContainerSpec
        image: !format localhost:5000/xl-demo-frontend:%appversion%
        profile: production
        replicas: "{{replicas}}"
        env:
          BACKEND_ENDPOINT: http://back-web-service
          FEATURE: !format UCCM <b>{{env}}</b>-xl-demo-frontend:%appversion%
        ports:
        - name: web
          type: uccm.ContainerPortSpec
          containerPort: "8000"
          servicePort: "80"
          exposeAsIngress: True
        mountedFiles:
        - name: config
          type: uccm.MountedFileSpec
          path: /opt/config/data
          isSensitive: False
          file: !file "../frontend/config.properties"
        - name: sensitive-config
          type: uccm.MountedFileSpec
          path: /opt/config/data_secured
          isSensitive: True
          file: !file "../frontend/secured-config.properties"
      - name: uccm test application availability
        type: smoketest.HttpRequestTest
        url: http://xl-demo-{{env}}.xl-demo-uccm-app.xebialabs.demo/
        expectedResponseText: Hello, world!

