apiVersion: xl-deploy/v1
kind: Environments
metadata:
  Environments-home: Environments/xl-demo
spec:
  - name: staging.conf
    type: udm.Dictionary
    entries:
      env: staging
      replicas: 1
      alternate.color: no-color
      is_canary: false
      canary_type: primary
      uccm.Container.canary: false
  - name: production.conf
    type: udm.Dictionary
    entries:
      env: production
      replicas: 3
      is_canary: false
      canary_type: primary
      uccm.Container.canary: false
      alternate.color: no-color

