apiVersion: xl-deploy/v1
kind: Environments
metadata:
  Environments-home: Environments/xl-demo
spec:
  - name: staging.conf
    type: udm.Dictionary
    entries:
      env: staging
      replicas: 1
      alternate.color: empty-staging
  - name: production.conf
    type: udm.Dictionary
    entries:
      env: production
      replicas: 3
      alternate.color: empty-prod


