apiVersion: xl-deploy/v1
kind: Environments
metadata:
  Environments-home: Environments/xl-demo
spec:
  - name: staging.conf
    type: udm.Dictionary
    entries:
      env: staging
      is_canary: false
      replicas: 1
      canary_type: primary
      BACKEND_ENDPOINT: backend
  - name: production.conf
    type: udm.Dictionary
    entries:
      env: production
      is_canary: false
      replicas: 3
      canary_type: primary
      BACKEND_ENDPOINT: backend
  - name: xl-demo-staging
    type: udm.Environment
    members:
    - ~Infrastructure/xl-demo/xl-demo-kube/xl-demo-staging
    - ~Infrastructure/xl-demo/localhost/test-runner-staging
    dictionaries:
    - ./staging.conf
  - name: xl-demo-production
    type: udm.Environment
    members:
    - ~Infrastructure/xl-demo/xl-demo-kube/xl-demo-production
    - ~Infrastructure/xl-demo/localhost/test-runner-production
    dictionaries:
    - ./production.conf


