apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Containers
  type: core.Directory
  children:
    - name: xl-demo-frontend
      type: udm.Application
      children:
      - name: !value appversion
        type: udm.DeploymentPackage
        deployables:
        - name: frontend.yaml
          type: k8s.ResourcesFile
          file: !file manifests/frontend.yml
        - name: ingress.yaml
          type: k8s.ResourcesFile
          file: !file manifests/ingress.json


